# Generated by Django 4.2.3 on 2025-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_payment_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
