# Generated by Django 4.2.3 on 2025-10-24 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_customuser_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bima_id', models.CharField(max_length=20, unique=True)),
                ('notification_type', models.CharField(choices=[('BOOK_BORROWED', 'Book Borrowed'), ('BOOK_RETURNED', 'Book Returned'), ('BOOK_OVERDUE', 'Book Overdue'), ('FINE_IMPOSED', 'Fine Imposed'), ('REMINDER', 'Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
