# Generated by Django 4.2.3 on 2024-10-24 17:05

from django.db import migrations

def fix_notifications_field(apps, schema_editor):
    """Fix notifications field that might be boolean instead of list"""
    CustomUser = apps.get_model('libapp', 'CustomUser')
    
    for user in CustomUser.objects.all():
        # Check if notifications is a boolean or not a list
        if isinstance(user.notifications, bool) or not isinstance(user.notifications, list):
            user.notifications = []
            user.save()
            print(f"Fixed notifications field for user: {user.username}")

def reverse_fix_notifications_field(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_payment_bank_name_payment_payment_method'),
    ]

    operations = [
        migrations.RunPython(fix_notifications_field, reverse_fix_notifications_field),
    ]
