# Generated by Django 4.2.3 on 2025-10-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_fix_notifications_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('book_type', models.CharField(choices=[('RELIGIOUS', 'Religious/Spiritual'), ('EDUCATIONAL', 'Educational'), ('LITERATURE', 'Literature'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='digital_book_covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='digital_books/pdf/')),
                ('word_file', models.FileField(blank=True, null=True, upload_to='digital_books/word/')),
                ('online_reading_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('download_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalBookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ONLINE_READING', 'Online Reading'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('access_start_date', models.DateTimeField()),
                ('access_end_date', models.DateTimeField()),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('digital_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='libapp.digitalbook')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='QRPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('digital_book_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payment', to='libapp.digitalbookaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='digitalbookaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
