# Generated by Django 4.2.3 on 2025-10-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_digitalbook_digitalbookaccess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.TextField(help_text='QR code data containing user information')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='user_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('VERIFICATION', 'Verification')], default='VERIFICATION', max_length=20)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, help_text='Location where scan occurred', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the scan', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
                ('scanned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Scan Log',
                'verbose_name_plural': 'QR Scan Logs',
                'ordering': ['-scan_timestamp'],
            },
        ),
    ]
